/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Asset: typeof import('./components/Asset/Asset.vue')['default']
    AssetActionMenu: typeof import('./components/Asset/AssetActionMenu.vue')['default']
    AssetCreateFolderDialog: typeof import('./components/Asset/AssetCreateFolderDialog.vue')['default']
    AssetGrid: typeof import('./components/AssetGrid.vue')['default']
    AssetRenameDialog: typeof import('./components/Asset/AssetRenameDialog.vue')['default']
    AssetsGrid: typeof import('./components/AssetsGrid.vue')['default']
    AssetToolButton: typeof import('./components/Asset/AssetToolButton.vue')['default']
    AssetUploadDialog: typeof import('./components/Asset/AssetUploadDialog.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./components/SideMenu.vue')['default']
    UtilsBar: typeof import('./components/UtilsBar.vue')['default']
  }
}
